### ISSUE TITLE
Задания, которые надо решить обязательно в течение недели (21-27 ноя)

### ISSUE THREAD

**Issue by komarovn** [nik709/MillShop#51]
1) Сделать вывод в itemPage названия globalCategory и subCategory (вверху их вставить надо с помощью javascript)
2) Добавить возможность установки глобальной категории setGlobalCategory(&category). Функция вызывается на страницах Men, Women, Kids. Нужна для вывода айтемов, соответствующих данной странице
3) Написать критерий отбора по subCategory (аналогично размерам и цветам)

**Comment by komarovn** [comment]
1. Выводить страницу 404, если в адресе указали несуществущее id, например
   http://millshop.com/site/pages/itemPage.php?ID=1200018

**Comment by nik709** [comment]
done
